import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { ordersApi } from '../services/api';
import LoadingSpinner from '../components/LoadingSpinner';
import DotsBackground3D from '../components/DotsBackground3D';

function statusClass(status) {
  const map = {
    delivered: 'bg-emerald-500/15 text-emerald-300 border-emerald-400/30',
    shipped: 'bg-sky-500/15 text-sky-300 border-sky-400/30',
    processing: 'bg-amber-500/15 text-amber-300 border-amber-400/30',
    pending: 'bg-slate-500/15 text-slate-300 border-slate-400/30',
    cancelled: 'bg-rose-500/15 text-rose-300 border-rose-400/30',
  };
  return map[String(status || '').toLowerCase()] || 'bg-indigo-500/15 text-indigo-300 border-indigo-400/30';
}

function formatMoney(amount) {
  return `LKR ${Number(amount || 0).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

export default function DashboardPage() {
  const { user, coupons } = useAuth();
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [downloadingId, setDownloadingId] = useState(null);
  const [showCoupons, setShowCoupons] = useState(false);

  useEffect(() => {
    ordersApi
      .list()
      .then((res) => setOrders(res.data.data || []))
      .finally(() => setLoading(false));
  }, []);

  const totalOrders = orders.length;
  const totalSpent = orders.reduce((sum, order) => sum + Number(order.total_amount || 0), 0);
  const completedOrders = orders.filter((order) =>
    ['delivered', 'shipped'].includes(String(order.status || '').toLowerCase())
  ).length;
  const processingOrders = orders.filter((order) =>
    ['pending', 'processing'].includes(String(order.status || '').toLowerCase())
  ).length;

  const buildReceiptHtml = (order, items) => {
    const rows = (items || [])
      .map(
        (item) => `
        <tr>
          <td style="padding:10px;border-bottom:1px solid #dbe4ff;">${item.name}</td>
          <td style="padding:10px;border-bottom:1px solid #dbe4ff;text-align:center;">${item.quantity}</td>
          <td style="padding:10px;border-bottom:1px solid #dbe4ff;text-align:right;">${formatMoney(item.price)}</td>
          <td style="padding:10px;border-bottom:1px solid #dbe4ff;text-align:right;">${formatMoney(Number(item.price) * Number(item.quantity))}</td>
        </tr>
      `
      )
      .join('');

    const paymentLabel = order.payment_method === 'card' ? 'Card Payment' : 'Cash on Delivery';

    return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>NeoCart Receipt #${order.id}</title>
  <style>
    body { font-family: Arial, sans-serif; background: radial-gradient(circle at top right, #1d4ed8 0%, #0f172a 45%, #050816 100%); margin: 0; padding: 28px; color: #e2e8f0; }
    .card { max-width: 920px; margin: 0 auto; background: linear-gradient(145deg, rgba(14,24,54,0.96), rgba(8,12,32,0.96)); border: 1px solid rgba(148, 163, 184, 0.2); border-radius: 22px; padding: 28px; box-shadow: 0 24px 60px rgba(15, 23, 42, 0.45); }
    .brand { font-size: 28px; font-weight: 800; margin: 0; color: #93c5fd; letter-spacing: 0.5px; }
    .meta { display:flex; justify-content: space-between; gap:16px; margin-top: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 18px; }
    .totals { margin-top: 16px; text-align: right; font-weight: 800; font-size: 22px; color: #93c5fd; }
    th { color: #cbd5e1; }
    td { color: #e2e8f0; }
    .note { margin-top: 12px; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="card">
    <h1 class="brand">NeoCart Payment Receipt</h1>
    <div class="meta">
      <div>
        <p><strong>Order ID:</strong> #${order.id}</p>
        <p><strong>Date:</strong> ${new Date(order.created_at).toLocaleString()}</p>
      </div>
      <div>
        <p><strong>Payment:</strong> ${paymentLabel}</p>
      </div>
    </div>
    <table>
      <thead>
        <tr>
          <th style="text-align:left;padding:10px;border-bottom:2px solid #bfdbfe;">Item</th>
          <th style="text-align:center;padding:10px;border-bottom:2px solid #bfdbfe;">Qty</th>
          <th style="text-align:right;padding:10px;border-bottom:2px solid #bfdbfe;">Unit Price</th>
          <th style="text-align:right;padding:10px;border-bottom:2px solid #bfdbfe;">Line Total</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
    <p class="totals">Total: ${formatMoney(order.total_amount)}</p>
    <p class="note">Thanks for your order. This receipt was generated by NeoCart.</p>
  </div>
</body>
</html>`;
  };

  const downloadReceipt = async (orderId) => {
    setDownloadingId(orderId);
    try {
      const res = await ordersApi.receipt(orderId);
      const data = res.data?.data || {};
      const order = data.order;
      const items = data.items || [];
      if (!order) {
        return;
      }

      const html = buildReceiptHtml(order, items);
      const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `neocart-receipt-${order.id}.html`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setDownloadingId(null);
    }
  };

  return (
    <div className="relative space-y-6 overflow-hidden rounded-3xl p-2">
      <DotsBackground3D />
      <section className="glass p-6 md:p-8">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-200/70">Account Overview</p>
            <h1 className="mt-2 text-3xl font-bold md:text-4xl">Welcome, {user?.name}</h1>
            <p className="mt-2 text-slate-300">Track your purchases, order status, and account activity in one place.</p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-right">
            <p className="text-xs text-slate-400">Member email</p>
            <p className="font-semibold">{user?.email}</p>
            <p className="mt-1 text-xs capitalize text-slate-400">Role: {user?.role}</p>
          </div>
        </div>

        <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <article className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs text-slate-400">Total Orders</p>
            <p className="mt-2 text-2xl font-bold">{totalOrders}</p>
          </article>
          <article className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs text-slate-400">Total Spent</p>
            <p className="mt-2 text-2xl font-bold text-blue-300">{formatMoney(totalSpent)}</p>
          </article>
          <article className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs text-slate-400">Completed Orders</p>
            <p className="mt-2 text-2xl font-bold text-emerald-300">{completedOrders}</p>
          </article>
          <article className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs text-slate-400">In Progress</p>
            <p className="mt-2 text-2xl font-bold text-amber-300">{processingOrders}</p>
          </article>
        </div>
      </section>

      <section className="glass p-6 md:p-8">
        <div className="flex items-end justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold md:text-2xl">Recent Orders</h2>
            <p className="mt-1 text-sm text-slate-400">Latest purchases and delivery progress.</p>
          </div>
          <button type="button" className="btn-secondary" onClick={() => setShowCoupons((value) => !value)}>
            {showCoupons ? 'Hide coupons' : 'Coupons'}
          </button>
        </div>

        {showCoupons ? (
          <div className="mt-4 rounded-2xl border border-white/10 bg-white/5 p-4">
            <h3 className="text-lg font-semibold">Collected coupons</h3>
            {coupons.length === 0 ? (
              <p className="mt-2 text-sm text-slate-400">No coupons collected yet. Go to Home and collect coupons.</p>
            ) : (
              <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {coupons.map((coupon) => (
                  <div key={coupon.code} className="rounded-xl border border-emerald-300/30 bg-emerald-500/10 p-3">
                    <p className="text-sm font-semibold text-emerald-300">{coupon.code}</p>
                    <p className="text-sm text-slate-200">{coupon.title}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : null}

        {loading ? (
          <div className="mt-6">
            <LoadingSpinner label="Loading orders" />
          </div>
        ) : orders.length === 0 ? (
          <div className="mt-5 rounded-2xl border border-dashed border-white/20 bg-white/5 p-6 text-center">
            <p className="text-slate-300">No orders yet.</p>
            <p className="mt-1 text-sm text-slate-400">Place your first order to start tracking it here.</p>
          </div>
        ) : (
          <div className="mt-5 overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead>
                <tr className="border-b border-white/10 text-slate-400">
                  <th className="py-3 pr-4">Order ID</th>
                  <th className="py-3 pr-4">Amount</th>
                  <th className="py-3 pr-4">Status</th>
                  <th className="py-3 pr-4">Payment</th>
                  <th className="py-3">Date</th>
                  <th className="py-3 text-right">Receipt</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((order) => (
                  <tr key={order.id} className="border-b border-white/5 text-slate-200">
                    <td className="py-3 pr-4 font-medium">#{order.id}</td>
                    <td className="py-3 pr-4 font-semibold text-blue-300">{formatMoney(order.total_amount)}</td>
                    <td className="py-3 pr-4">
                      <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${statusClass(order.status)}`}>
                        {order.status}
                      </span>
                    </td>
                    <td className="py-3 pr-4 capitalize text-slate-300">{String(order.payment_method || 'cash_on_delivery').replaceAll('_', ' ')}</td>
                    <td className="py-3 text-slate-300">{new Date(order.created_at).toLocaleString()}</td>
                    <td className="py-3 text-right">
                      <button
                        type="button"
                        className="btn-secondary px-3 py-2 text-xs"
                        disabled={downloadingId === order.id}
                        onClick={() => downloadReceipt(order.id)}
                      >
                        {downloadingId === order.id ? 'Downloading...' : 'Download receipt'}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
